language: android

branches:
  only:
    - master

before_install:
    - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
    - export ANDROID_NDK_HOME=$HOME/android-ndk-root

script: ./mosquitto_android_cmake.sh

notifications:
  email:
    recipients:
      - vungoctrong@gmail.com
    on_success: change
    on_failure: always